# site settings
title: Moar Guitars 
subtitle: Hand made in Copenhagen
email: mail@moarguitars.com
description:  
baseurl: "/moarguitars" # the subpath of your site, e.g. /blog
url: https://moarguitars.github.io # the base hostname & protocol for your site
author:
street_address: 
city: Copenhagen S
state: 
zip_code: 
country: Denmark
phone: (0045) 5387 2888
permalink: /:title/

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url: https://www.facebook.com/moarguitars/ 
instagram_url: https://www.instagram.com/moarguitars/
linkedin_url: 

# build settings
markdown: kramdown

sass:
  style: compressed

# sitemap
plugins:
  - jekyll-sitemap