# site settings
title: Moar Guitars 
subtitle: Hand-made in Copenhagen
email: mail@johnhayn.es
description:  The world's local guitar builder. My unique and carefully hand-crafted guitars are played on stages all around the world, but each one starts its journey from my workshop in Copenhagen, Denmark.
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://www.moarguitars.com # the base hostname & protocol for your site
author:
street_address: 
city: Copenhagen S
state: 
zip_code: 
country: Denmark
phone: (0045) 5387 2888
permalink: /:title/

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings
facebook_url: https://www.facebook.com/moarguitars/ 
instagram_url: https://www.instagram.com/moarguitars/
youtube_url: https://www.youtube.com/channel/UCyS4fZAUkx7QRkcIcBEnytA/videos

# build settings
markdown: kramdown

sass:
  style: compressed

# sitemap
plugins:
  - jekyll-sitemap
  - jekyll-airtable
