# site settings
title: Moar Guitars | Handmade in Copenhagen
subtitle: 2020
email: mail@moarguitars.com
description:  Totally hand made guitars from Copenhagen, Denmark. I exclusively use the best quality woods, top end hardware, and custom boutique pickups built to the customers specifications to create a guitar that has a timeless feel, unmatched playability and sculpted tone that will last a lifetime.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://moarguitars.github.io/moarguitars/ # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 
permalink: /:title/

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url: https://www.facebook.com/moarguitars/ 
instagram_url: https://www.instagram.com/moarguitars/
linkedin_url: 
twitter_url: http://moarguitars.com/#

# build settings
markdown: kramdown

sass:
  style: compressed

# sitemap
url: "https://thegreatfire.co.uk" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap