# site settings
title: Moar Guitars | Hand made in Copenhagen
subtitle: 2020
email: mail@moarguitars.com
description:  Totally hand made guitars from Copenhagen, Denmark. I exclusively use the best quality woods, top end hardware, and custom boutique pickups built to the customers specifications to create a guitar that has a timeless feel, unmatched playability and sculpted tone that will last a lifetime.
baseurl: "/moarguitars" # the subpath of your site, e.g. /blog
url: http://moarguitars.github.io # the base hostname & protocol for your site
author:
street_address: 
city: Amager
state: Copenhagen
zip_code: 
country: Denmark
phone: 
permalink: /:title/

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
facebook_url: https://www.facebook.com/moarguitars/ 
instagram_url: https://www.instagram.com/moarguitars/
linkedin_url: 
twitter_url: http://twitter.com/moarguitars

# build settings
markdown: kramdown

sass:
  style: compressed

# sitemap
plugins:
  - jekyll-sitemap